version: '3'
services:
   myapp:
     build: . 
     ports : 
       - "5000:5000"
     depends_on:
      - redis
     networks:
      - app-network

   redis:
      image : "redis:alpine"
      ports : 
       - "6379:6379"
      networks:
        - app-network
networks:
   app-network:
       driver: bridge 
